version: "3"

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      - mariadb
    expose:
      - "9000"
    volumes:
      - wp:/var/www/rel-fila/wordpress
    env_file: .env
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/rel-fila/wordpress
    env_file: .env
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/$HOME/data/wordpress'
  db:
    driver: local
    name: db
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/$HOME/data/mariadb'
